name: Benchmark
on:
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.1

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm build

      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Start Yoga Server
        working-directory: ./benchmark/hello-world
        run: |
          pnpm start &
          pnpm wait-on tcp:4000
        env:
          NODE_NO_WARNINGS: true
          NODE_ENV: production
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Start and Report Yoga Benchmark
        working-directory: ./benchmark/hello-world
        run: k6 -e GITHUB_PR=${{ github.event.number }} -e GITHUB_SHA=${{ github.sha }} -e GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} run k6.js
